### PR TITLE
Systemd service

### LINKED ISSUE #7: Create a systemd service!
As the title reads, make it install-able as a service on a Linux system as a service.

### PR DESCRIPTION
**Pull request by euronay**
Fixes #7

Hi

I've packaged this up as a Systemd service. I've added instructions to deploy and run to the README, so please do give it a go and let me know what you think!

I had to change it to use a proper logging implementation rather than writing to the console. I hope this is OK.

Cheers

James

### CODE REVIEW

**Comment by Krutonium** [comment]
So I accidentally broke your PR with a push before I noticed this, so I'll just be over here adding my changes to yours and then I'll merge the two.

**Comment by Krutonium** [comment]
Do me a favor and tell me if this all looks correct to you.

**Comment by euronay** [comment]
No probs, it looks OK to me - the main thing is if it works an whether you are happy with the approach.

The only thing I would say is that you could probably dependency inject the configuration into the service rather than construct it, but it's something I can tidy up later. I probably won't be able to look at it again until tomorrow night - up to you if you want to merge it in as it stands or wait....

**Comment by Krutonium** [comment]
I'm going to merge it, but I would love to see how you inject the configuration - I honestly have never done that so I am curious.

**Pull request merged**
